{{ if $.Values.settings.syncJobs.website -}}
{{ range $index, $websiteJob := $.Values.settings.syncJobs.website }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kiss-frontend.fullname" $ }}-crawler-website-{{ $index }}
  labels:
    {{- include "kiss-frontend.labels" $ | nindent 4 }}
data:
  crawler.yml: |
    domains:
      - url: {{ $websiteJob.domain }}
        exclude_tags:
          {{- range (default (list "header" "footer" "nav") $websiteJob.excludeTags) }}
          - {{ . }}
          {{- end }}
        {{- if $websiteJob.crawlRules }}
        crawl_rules:
          {{- toYaml $websiteJob.crawlRules | nindent 10 }}
        {{- end }}
    output_sink: elasticsearch
    output_index: {{ default (printf "search-%s" ($websiteJob.sourceName | lower | replace " " "-")) $websiteJob.outputIndex }}
    {{- if $websiteJob.maxCrawlDepth }}
    max_crawl_depth: {{ $websiteJob.maxCrawlDepth }}
    {{- end }}
    {{- if $websiteJob.maxExtractedLinksCount }}
    max_extracted_links_count: {{ $websiteJob.maxExtractedLinksCount }}
    {{- end }}
    {{- if $websiteJob.maxUniqueUrlCount }}
    max_unique_url_count: {{ $websiteJob.maxUniqueUrlCount }}
    {{- end }}
    {{- if not (kindIs "invalid" $websiteJob.purgeCrawlEnabled) }}
    purge_crawl_enabled: {{ $websiteJob.purgeCrawlEnabled }}
    {{- end }}
    {{- if not (kindIs "invalid" $websiteJob.fullHtmlExtractionEnabled) }}
    full_html_extraction_enabled: {{ $websiteJob.fullHtmlExtractionEnabled }}
    {{- end }}
    {{- if $websiteJob.userAgent }}
    user_agent: {{ $websiteJob.userAgent }}
    {{- end }}
    {{- if $websiteJob.threadsPerCrawl }}
    threads_per_crawl: {{ $websiteJob.threadsPerCrawl }}
    {{- end }}
    binary_content_extraction_enabled: true
    binary_content_extraction_mime_types:
      - application/pdf
      - application/msword
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    log_level: info
    event_logs_to_file: false
    system_logs_to_file: false
    elasticsearch:
      host: {{ $.Values.settings.elastic.baseUrl }}
      port: 443
      username: {{ $.Values.settings.elastic.username }}
      password: {{ $.Values.settings.elastic.password }}
      bulk_api:
        max_items: 100
        max_size_bytes: 1048576
{{- end }}
{{- end }}
